pointcloud_to_laserscan:
  ros__parameters:
    scan_time: 0.1
    range_min: 0.3
    range_max: 100.0
    angle_min: -3.14159  # -180 deg
    angle_max: 3.14159   # 180 deg
    angle_increment: 0.0087  # ~0.5 deg, 调整基于mid360分辨率
    target_frame: body   # 输出scan的frame，与base_link一致
    transform_tolerance: 0.01
    min_height: -0.9     # 投影高度范围 (假设地面附近)
    max_height: -0.7
    use_inf: true
    inf_epsilon: 1.0
    concurrency_level: 0
