# LiDAR-IMU紧耦合参数配置文件
# 点云和IMU话题配置
# 点云角度范围在±120度，见src/fastlio2/src/utils.cpp中的过滤设置

imu_topic: /livox/imu
lidar_topic: /livox/lidar
body_frame: base_link
world_frame: odom
print_time_cost: false

# 室内优化参数
lidar_filter_num: 4             # LiDAR滤波数量6
lidar_min_range: 0.3         # LiDAR最小探测距离(米)0.5
lidar_max_range: 30.0

# 地图和扫描参数
scan_resolution: 0.15           # 减小扫描分辨率，提高点云密度0.15#0.1 #0.15
map_resolution: 0.2            # 减小地图分辨率0.2

cube_len: 300
det_range: 30.0
# 运动约束
move_thresh: 0.1               # 减小移动阈值，更频繁更新地图1.0#0.5#0.1

#IMU噪声参数调整（减小漂移）
#振荡
na: 0.3                   # 减小加速度计噪声0.05#0.5#0.8#0.6#0.3
ng: 0.3                     # 显著减小陀螺仪噪声0.05#0.5#0.8#0.6#0.3
#漂移
nba: 0.0003                   # 减小加速度计偏置噪声0.0005#0.005  
nbg: 0.0001                   # 减小陀螺仪偏置噪声0.0005#0.005
imu_init_num: 20               # 保持IMU初始化数据点数

# na: 1.0      # 加速度计测量噪声（已正确）
# ng: 1.0      # 陀螺仪测量噪声（已正确）
# nba: 0.00006     # 必须 < 0.0001！偏置游走噪声
# nbg: 0.000011    # 必须 < 0.00002！极小
# imu_init_num: 200 # 增加到 200 帧（2秒 @ 100Hz）

# 点云匹配参数优化
lidar_cov_inv: 1500.0          # 提高LiDAR权重，增强匹配约束1500
near_search_num: 3            # 增加最近邻搜索数量，提高匹配精度12#3
ieskf_max_iter: 4             # 增加IEKF迭代次数10#3#$

gravity_align: true              # 重力对齐
esti_il: false                    # 在线估计IMU-LiDAR外参false

# 外参保持不变（确保准确标定）
t_il: [-0.011, -0.02329, 0.04412]
r_il: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]


