pointcloud_to_laserscan:
  ros__parameters:
    scan_time: 0.1   #10hz/s#0.1
    range_min: 0.3
    range_max: 10.0   #100#30
    angle_min: -3.14159  # -180 deg
    angle_max: 3.14159   # 180 deg
    angle_increment: 0.007  # ~0.5 deg, 调整基于mid360分辨率0.0087  #0.007~0.4du
    target_frame: base_link   # 输出scan的frame，与base_link一致 body#lidar#map
    transform_tolerance: 0.02 #0.01#1
    max_height: 1.2	 # 对齐pcd2pgm设置1.2
    min_height: -1.2    # 投影高度范围-0.4
    use_inf: true
    inf_epsilon: 1.0   #1.0
    concurrency_level: 0
    
    queue_size: 60 #20
    time_increment: 0.000111
